name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '14', '16']
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set TimeZone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Singapore"
        timezoneMacos: "Asia/Singapore"
        timezoneWindows: "Singapore Standard Time"
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
      env:
        CI: true
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
