name: Release
on: workflow_dispatch
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Set TimeZone
              uses: szenius/set-timezone@v1.0
              with:
                  timezoneLinux: 'Asia/Singapore'
                  timezoneMacos: 'Asia/Singapore'
                  timezoneWindows: 'Singapore Standard Time'
            - name: Install dependencies
              run: yarn install
            - name: Build
              run: yarn run build
            - name: UT
              run: yarn test
            - name: Delete hooks
              run: rm -rf ./.git/hooks
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn run semantic-release
